name: check code(Nodejs v19)

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: nodejs Setup v19
      uses: actions/setup-node@v3
      with:
        node-version: 19
    - name: package install
      run: npm i
    - name: ci Setup
      run: npm ci

    - name: run reviewdog
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-check
        eslint_flags: 'src/'
    - name: run check build
      run: npm run build